<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>testmind</groupId><artifactId>tools</artifactId><version>1</version>
  <dependencies>
    <dependency><groupId>com.intuit.karate</groupId><artifactId>karate-core</artifactId><version>1.4.1</version></dependency>
    <dependency><groupId>org.jacoco</groupId><artifactId>org.jacoco.cli</artifactId><version>0.8.15</version><classifier>nodeps</classifier><type>jar</type></dependency>
  </dependencies>
</project>
