"""Survey + protect the A-skill trees against the recurring truncation-to-empty bug.

Read-only survey:   python scripts/protect_trees.py
Apply git baseline: python scripts/protect_trees.py --apply

A file is "damaged" when it is 0 bytes or exactly 2 bytes of CRLF -- the two
signatures left by the 2026-09-07 21:49 burst (Clear-Content -> 0 bytes,
Set-Content -Value "" -> "\r\n").

Trees with no .git are the reason the damage was unrecoverable: test-Mind's
mcp.py could only be rebuilt from a stale .pyc. Putting every tree under git
makes any future truncation a one-command restore and makes `git status` an
instant detector, which is why this is the permanent fix rather than a watchdog.
"""
import os
import subprocess
import sys
import time

DEFAULT_ROOTS = [
    r"E:\workA\A-skill",
    r"E:\AAAAAA\A-skill-work",
    # Listed separately as well: as a whole each parent exceeds the size cap and is
    # skipped, which would leave headroom-main -- the one subtree with confirmed
    # damage -- unprotected. Per-subtree, each is judged on its own size.
    r"E:\AAAAAA\A-skill-work\github-skill",
    r"E:\AAAAAA\github-skill",
    r"E:\AAAAAA\github-skill\A-github",
]
SKIP_DIRS = {".git", "node_modules", ".venv", "venv", "__pycache__", ".pytest_cache",
             "dist", "build", ".next", "target", ".context-compress", ".data", ".uv-cache"}
SKIP_EXT = {".pyc", ".pyo", ".class", ".jar", ".png", ".jpg", ".jpeg", ".gif",
            ".ico", ".zip", ".gz", ".db", ".sqlite", ".woff", ".woff2", ".ttf",
            ".pdf", ".exe", ".dll", ".so", ".mp4", ".lock"}

# Empty on purpose. Counting these as truncation conflates a test run's sut.log or
# a ComfyUI model-dir placeholder with real damage, and buries the files at risk.
BENIGN_EMPTY = {".gitkeep", ".keep", "py.typed"}
BENIGN_EXT = {".log"}
BENIGN_DIRS = ("reports", "logs")

# Cannot be judged by name. Most __init__.py files are legitimately empty, but
# headroom-main's providers/cursor/__init__.py was truncated to 0 bytes while the
# installed copy still held 307 bytes of real re-exports -- so these are reported
# separately rather than silently dropped or counted as confirmed damage.
AMBIGUOUS_EMPTY = {"__init__.py"}

GITIGNORE = """# generated by protect_trees.py
node_modules/
.venv/
venv/
__pycache__/
*.pyc
.pytest_cache/
dist/
build/
target/
*.log
*.db
.context-compress/
.data/
.uv-cache/
"""

# Written to .git/info/exclude, NOT the working tree: a tree whose .gitignore was
# itself truncated to 2 bytes would otherwise defeat it. These trees hold credential
# material (headroom.local.env, *.local.json, mcp.json with live DB passwords), and a
# protection baseline that commits secrets is worse than no baseline at all.
#
# Every pattern is basename-anchored. Substring patterns are actively harmful here:
# a `*secret*` rule kept 24 real source files (secrets-service.ts,
# use-create-secret.ts, redact-mcp-secrets.test.ts) and two secrets-settings/
# directories out of project-brain-agent's baseline, so the files most likely to be
# edited by an agent were the ones left unrecoverable.
SECRETS = """# credential material only -- precise names, never substring matches
.env
.env.*
!.env.example
!.env.sample
!.env.template
*.env
!*.env.example
!*.env.sample
!*.env.template
*.local.json
*.local.yaml
*.local.yml
credentials.json
credentials.yaml
credentials.yml
id_rsa
id_rsa.*
*.pem
*.key
*.p12
*.pfx
mcp.json
"""

SECRET_EXTS = {".pem", ".key", ".p12", ".pfx"}
TEMPLATES = (".example", ".sample", ".template")


def is_secret_path(rel):
    """Mirror of the SECRETS patterns, applied in Python so the hold-back can be
    reported. Deliberately extension-aware: `mcp-redacted-credentials.ts` is source
    code and must be tracked, while `credentials.json` is config and must not be."""
    base = os.path.basename(rel.replace("\\", "/")).lower()
    ext = os.path.splitext(base)[1]
    if ext in SECRET_EXTS:
        return True
    if base == "mcp.json" or base.startswith("id_rsa"):
        return True
    if base in ("credentials.json", "credentials.yaml", "credentials.yml"):
        return True
    if base.endswith((".local.json", ".local.yaml", ".local.yml")):
        return True
    if base == ".env" or ext == ".env" or base.startswith(".env."):
        return not any(base.endswith(s) for s in TEMPLATES)
    return False


def is_damaged(path):
    try:
        sz = os.path.getsize(path)
    except OSError:
        return False, 0
    if sz == 0:
        return True, 0
    if sz == 2:
        try:
            with open(path, "rb") as f:
                return f.read(2) == b"\r\n", 2
        except OSError:
            return False, 2
    return False, sz


def is_benign_empty(rel, fn):
    """True for files that are allowed to be empty: packaging markers, logs,
    model-directory placeholders, and anything under a test-output directory."""
    if fn in BENIGN_EMPTY or os.path.splitext(fn)[1].lower() in BENIGN_EXT:
        return True
    if fn.startswith("put_") and fn.endswith("_here"):
        return True                     # ComfyUI ships these as 0-byte markers
    parents = [c.lower() for c in rel.replace("\\", "/").split("/")[:-1]]
    return any(c in BENIGN_DIRS for c in parents)


def scan(tree):
    """Returns (files_seen, confirmed_damaged, ambiguous_empty)."""
    damaged, ambiguous, total = [], [], 0
    for dirpath, dirnames, filenames in os.walk(tree):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            ext = os.path.splitext(fn)[1].lower()
            if ext in SKIP_EXT:
                continue
            p = os.path.join(dirpath, fn)
            if os.path.islink(p):
                continue
            total += 1
            bad, sz = is_damaged(p)
            if not bad:
                continue
            rel = os.path.relpath(p, tree)
            if is_benign_empty(rel, fn):
                continue
            stamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(os.path.getmtime(p)))
            (ambiguous if fn in AMBIGUOUS_EMPTY else damaged).append((rel, sz, stamp))
    return total, damaged, ambiguous


def git(tree, *args):
    return subprocess.run(["git", "-C", tree, *args], capture_output=True)


# Measured across these roots: everything above 100 MB is a re-downloadable upstream
# clone with no first-party work (codegraph-main 191 MB, A-github/8-27 170 MB of
# ComfyUI, A-github/8-29 900 MB), while headroom-main at 83 MB does carry local
# modifications and was the only such subtree with confirmed damage. A baseline has
# to stay cheap enough to refresh often, so big vendored drops are left out.
MAX_TREE_MB = 100


def tree_bytes(tree):
    total = 0
    for dirpath, dirnames, filenames in os.walk(tree):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            try:
                total += os.path.getsize(os.path.join(dirpath, fn))
            except OSError:
                continue
    return total


def write_exclude(tree):
    exclude = os.path.join(tree, ".git", "info", "exclude")
    os.makedirs(os.path.dirname(exclude), exist_ok=True)
    with open(exclude, "w", encoding="utf-8") as f:
        f.write(SECRETS)


def stage_and_hold(tree):
    """Stage everything, then unstage genuine secrets. Returns the held paths."""
    git(tree, "add", "-A")
    staged = git(tree, "diff", "--cached", "--name-only", "-z").stdout.decode("utf-8", "replace")
    held = [p for p in staged.split("\0") if p and is_secret_path(p)]
    if held:
        git(tree, "reset", "-q", "--", *held)
        print("    HELD BACK %d secret path(s):" % len(held))
        for p in held[:10]:
            print("      - %s" % p)
        if len(held) > 10:
            print("      ... and %d more" % (len(held) - 10))
    return held


def report_gitlinks(tree):
    """A gitlink records a nested repo as one entry with none of its files, so the
    outer baseline protects nothing inside it -- the nested tree needs its own."""
    out = git(tree, "ls-files", "-s")
    links = [ln.split("\t", 1)[1] for ln in out.stdout.decode("utf-8", "replace").splitlines()
             if ln.startswith("160000")]
    for g in links:
        sub = os.path.join(tree, g.replace("/", os.sep))
        own = os.path.isdir(os.path.join(sub, ".git"))
        print("    gitlink %s -> %s" % (g, "nested repo, protected separately" if own
                                        else "NOT PROTECTED (no .git of its own)"))
    return links


def commit(tree, msg):
    r = git(tree, "-c", "user.name=protect_trees", "-c", "user.email=protect@local",
            "commit", "-q", "-m", msg)
    if r.returncode == 0:
        h = git(tree, "rev-parse", "--short", "HEAD").stdout.decode().strip()
        n = git(tree, "ls-files").stdout.decode().count("\n")
        print("    -> committed %s (%d files tracked)" % (h, n))
        return True
    print("    -> commit FAILED: %s"
          % (r.stdout.decode("utf-8", "replace") + r.stderr.decode("utf-8", "replace"))[:160])
    return False


def damage_note(damaged):
    if not damaged:
        return "扫描未发现被截断文件。"
    msg = "已知被截断文件 %d 个（0/2 字节），本次一并入库以固定现状，\n" % len(damaged)
    msg += "清单见下；这些文件内容已丢失，不要误认为有意为之：\n"
    for rel, sz, mt in sorted(damaged):
        msg += "  - %s (%dB, %s)\n" % (rel, sz, mt)
    return msg


def baseline(tree, damaged):
    r = git(tree, "init", "-q")
    if r.returncode != 0:
        print("    git init FAILED: %s" % r.stderr.decode("utf-8", "replace")[:120])
        return
    write_exclude(tree)

    gi = os.path.join(tree, ".gitignore")
    gi_bad = os.path.exists(gi) and is_damaged(gi)[0]
    if not os.path.exists(gi) or gi_bad:
        with open(gi, "w", encoding="utf-8") as f:
            f.write(GITIGNORE)
        if gi_bad:
            print("    note: existing .gitignore was truncated; rewritten")

    stage_and_hold(tree)
    commit(tree, "建立恢复基线：防截断保护（protect_trees.py）\n\n" + damage_note(damaged))
    report_gitlinks(tree)


def is_our_baseline(tree):
    """True only for repos whose HEAD commit this script authored, so refresh() can
    never restage a pre-existing user repo (NexMind, Token-Mind, test-Mind, A-data)."""
    r = git(tree, "log", "-1", "--format=%s")
    return r.returncode == 0 and b"protect_trees.py" in r.stdout


def refresh(tree, damaged):
    """Correct a baseline this script already authored. Only called when HEAD carries
    our marker, so a pre-existing user repo is never restaged."""
    write_exclude(tree)
    before = git(tree, "ls-files").stdout.decode().count("\n")
    stage_and_hold(tree)
    if git(tree, "diff", "--cached", "--quiet").returncode == 0:
        print("    -> refresh: exclude already precise, %d files tracked" % before)
        report_gitlinks(tree)
        return
    ok = commit(tree, "修正恢复基线：排除规则改为精确匹配（protect_trees.py）\n\n"
                      "此前的 *secret* 等子串规则把真实源码误排除在基线之外\n"
                      "（如 secrets-service.ts、use-create-secret.ts），本次补录。\n\n"
                      + damage_note(damaged))
    if ok:
        after = git(tree, "ls-files").stdout.decode().count("\n")
        print("    -> refresh: %d -> %d files tracked (+%d)" % (before, after, after - before))
    report_gitlinks(tree)


def main():
    args = sys.argv[1:]
    apply = "--apply" in args
    force = "--force" in args
    roots = [a for a in args if not a.startswith("--")] or DEFAULT_ROOTS

    print("=" * 78)
    print("tree protection survey%s" % ("  [APPLY MODE]" if apply else "  [read-only]"))
    print("=" * 78)
    summary = []
    grand_damaged = 0
    grand_ambiguous = 0

    for ROOT in roots:
        if not os.path.isdir(ROOT):
            print("\n!! root absent: %s" % ROOT)
            continue
        print("\n### root %s" % ROOT)
        trees = sorted(
            d for d in os.listdir(ROOT)
            if os.path.isdir(os.path.join(ROOT, d)) and not d.startswith(".")
        )
        for t in trees:
            tree = os.path.join(ROOT, t)
            has_git = os.path.isdir(os.path.join(tree, ".git"))
            total, damaged, ambiguous = scan(tree)
            grand_damaged += len(damaged)
            grand_ambiguous += len(ambiguous)
            mb = tree_bytes(tree) / (1024 * 1024)
            action = "OWN-REPO" if has_git else "NO"
            print("\n%-26s git=%-5s files=%-6d damaged=%-4d ambiguous=%-3d %.1f MB"
                  % (t, "yes" if has_git else "NO", total, len(damaged), len(ambiguous), mb))
            for rel, sz, mt in sorted(damaged)[:8]:
                print("    %2dB  %-19s %s" % (sz, mt, rel))
            if len(damaged) > 8:
                print("    ... and %d more" % (len(damaged) - 8))

            if apply:
                if has_git:
                    if is_our_baseline(tree):
                        refresh(tree, damaged)
                        action = "REFRESHED"
                    # otherwise a pre-existing user repo: never restage
                elif total == 0:
                    # nothing to protect; baselining would create a repo whose only
                    # tracked file is the .gitignore we just wrote
                    print("    SKIPPED: no files to protect")
                    action = "SKIP-EMPTY"
                elif mb > MAX_TREE_MB and not force:
                    print("    SKIPPED: %.1f MB exceeds the %d MB baseline cap (use --force)"
                          % (mb, MAX_TREE_MB))
                    action = "SKIP-CAP"
                else:
                    baseline(tree, damaged)
                    action = "NEW"

            summary.append(("%s/%s" % (os.path.basename(ROOT), t), action, total,
                            len(damaged), len(ambiguous), mb))

    print("\n" + "=" * 78)
    print("%-40s %-10s %-8s %-9s %-8s %s" % ("TREE", "ACTION", "FILES", "DAMAGED", "AMBIG", "MB"))
    for name, action, total, d, a, mb in summary:
        print("%-40s %-10s %-8d %-9d %-8d %.1f" % (name, action, total, d, a, mb))
    print("-" * 78)
    print("confirmed damage: %d      ambiguous (__init__.py, needs case-by-case): %d"
          % (grand_damaged, grand_ambiguous))
    return 0


if __name__ == "__main__":
    sys.exit(main())
