"""Survey + protect the A-skill trees against the recurring truncation-to-empty bug.

Read-only survey:   python scripts/protect_trees.py
Apply git baseline: python scripts/protect_trees.py --apply

A file is "damaged" when it is 0 bytes or exactly 2 bytes of CRLF -- the two
signatures left by the 2026-09-07 21:49 burst (Clear-Content -> 0 bytes,
Set-Content -Value "" -> "\r\n").

Trees with no .git are the reason the damage was unrecoverable: test-Mind's
mcp.py could only be rebuilt from a stale .pyc. Putting every tree under git
makes any future truncation a one-command restore and makes `git status` an
instant detector, which is why this is the permanent fix rather than a watchdog.
"""
import os
import subprocess
import sys
import time

ROOT = r"E:\workA\A-skill"
SKIP_DIRS = {".git", "node_modules", ".venv", "venv", "__pycache__", ".pytest_cache",
             "dist", "build", ".next", "target", ".context-compress", ".data"}
SKIP_EXT = {".pyc", ".pyo", ".class", ".jar", ".png", ".jpg", ".jpeg", ".gif",
            ".ico", ".zip", ".gz", ".db", ".sqlite", ".woff", ".woff2", ".ttf",
            ".pdf", ".exe", ".dll", ".so", ".mp4", ".lock"}

GITIGNORE = """# generated by protect_trees.py
node_modules/
.venv/
venv/
__pycache__/
*.pyc
.pytest_cache/
dist/
build/
target/
*.log
*.db
.context-compress/
.data/
"""


def is_damaged(path):
    try:
        sz = os.path.getsize(path)
    except OSError:
        return False, 0
    if sz == 0:
        return True, 0
    if sz == 2:
        try:
            with open(path, "rb") as f:
                return f.read(2) == b"\r\n", 2
        except OSError:
            return False, 2
    return False, sz


def scan(tree):
    damaged, total = [], 0
    for dirpath, dirnames, filenames in os.walk(tree):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            ext = os.path.splitext(fn)[1].lower()
            if ext in SKIP_EXT:
                continue
            p = os.path.join(dirpath, fn)
            if os.path.islink(p):
                continue
            total += 1
            bad, sz = is_damaged(p)
            if bad:
                damaged.append((os.path.relpath(p, tree), sz,
                                time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(os.path.getmtime(p)))))
    return total, damaged


def git(tree, *args):
    return subprocess.run(["git", "-C", tree, *args], capture_output=True)


def main():
    apply = "--apply" in sys.argv
    trees = sorted(d for d in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, d)))
    print("=" * 78)
    print("A-skill tree protection survey%s" % ("  [APPLY MODE]" if apply else "  [read-only]"))
    print("=" * 78)
    grand_damaged = 0
    summary = []
    for t in trees:
        tree = os.path.join(ROOT, t)
        has_git = os.path.isdir(os.path.join(tree, ".git"))
        total, damaged = scan(tree)
        grand_damaged += len(damaged)
        summary.append((t, has_git, total, len(damaged)))
        print("\n%-22s git=%-5s files=%-6d damaged=%d"
              % (t, "yes" if has_git else "NO", total, len(damaged)))
        for rel, sz, mt in sorted(damaged)[:12]:
            print("    %2dB  %-19s %s" % (sz, mt, rel))
        if len(damaged) > 12:
            print("    ... and %d more" % (len(damaged) - 12))

        if apply and not has_git:
            if not os.path.exists(os.path.join(tree, ".gitignore")):
                with open(os.path.join(tree, ".gitignore"), "w", encoding="utf-8") as f:
                    f.write(GITIGNORE)
            r = git(tree, "init", "-q")
            if r.returncode != 0:
                print("    git init FAILED: %s" % r.stderr.decode("utf-8", "replace")[:120])
                continue
            git(tree, "add", "-A")
            msg = "建立恢复基线：防截断保护（protect_trees.py）\n\n"
            if damaged:
                msg += "已知被截断文件 %d 个（0/2 字节），本次一并入库以固定现状，\n" % len(damaged)
                msg += "清单见下；这些文件内容已丢失，不要误认为有意为之：\n"
                for rel, sz, mt in sorted(damaged):
                    msg += "  - %s (%dB, %s)\n" % (rel, sz, mt)
            else:
                msg += "扫描未发现被截断文件。"
            r = git(tree, "-c", "user.name=protect_trees", "-c", "user.email=protect@local",
                    "commit", "-q", "-m", msg)
            if r.returncode == 0:
                h = git(tree, "rev-parse", "--short", "HEAD").stdout.decode().strip()
                n = git(tree, "ls-files").stdout.decode().count("\n")
                print("    -> committed %s (%d files tracked)" % (h, n))
            else:
                print("    -> commit FAILED: %s"
                      % (r.stdout.decode("utf-8", "replace") + r.stderr.decode("utf-8", "replace"))[:160])

    print("\n" + "=" * 78)
    print("%-22s %-6s %-8s %s" % ("TREE", "GIT", "FILES", "DAMAGED"))
    for t, g, total, d in summary:
        print("%-22s %-6s %-8d %d" % (t, "yes" if g else ("NEW" if apply else "NO"), total, d))
    print("-" * 78)
    print("total damaged in A-skill: %d" % grand_damaged)
    return 0


if __name__ == "__main__":
    sys.exit(main())
