#!/usr/bin/env python
# scripts/v9_drift_to_regression.py — V9 §11 阶段 1+2 最小区段
# 读 v8_drift.json -> 边界 P0 cases -> 可直接喂给 TestMind run_pipeline
import json, re, sys
from pathlib import Path

# 路径：以 test-mind/ 为 cwd
ROOT = Path(".")
SUT  = ROOT / "examples" / "red-packet" / "sut.py"
E2E  = ROOT / "examples" / "red-packet" / "e2e.py"
DRIFT_IN = ROOT / "reports" / "v8_drift.json"
OUT_YAML  = ROOT / "reports" / "v9_regression_cases.yaml"
OUT_JSON  = ROOT / "reports" / "v9_regression_cases.json"

def parse_constraints(sut_text: str):
    out = []
    for line in sut_text.splitlines():
        i = line.find("CHECK(")
        if i < 0: continue
        outer = i + 5
        depth, end = 1, None
        for j in range(outer + 1, len(line)):
            if line[j] == "(": depth += 1
            elif line[j] == ")":
                depth -= 1
                if depth == 0: end = j; break
        if end is None: continue
        expr = line[outer+1:end]
        m = re.search(r"BETWEEN\s+(\d+)\s+AND\s+(\d+)", expr)
        if not m: continue
        cm = re.match(r"\s*(\w+)\s+", line)
        if not cm: continue
        out.append({"field": cm.group(1), "min": int(m.group(1)), "max": int(m.group(2))})
    return out

def test_signals(e2e_text: str, field: str):
    if field == "amount_cents":
        return [int(v) for v in re.findall(r"amount_cents[\"']?\s*[:=]\s*(\d+)", e2e_text)]
    if field == "quantity":
        return [int(v) for v in re.findall(r"\"quantity\"\s*:\s*(\d+)", e2e_text)]
    if field == "name":
        return [len(s) for s in re.findall(r"\"name\"\s*:\s*[\"']([^\"']*)[\"']", e2e_text)]
    return []

def build_body(field, v):
    if field == "amount_cents":
        return {"name": "边界", "amount_cents": v, "quantity": 1, "influencer_id": 1, "created_by": 1, "unlimited": False}
    if field == "quantity":
        return {"name": "边界", "amount_cents": 100, "quantity": v, "influencer_id": 1, "created_by": 1, "unlimited": False}
    if field == "name":
        return {"name": "x" * v, "amount_cents": 100, "quantity": 1, "influencer_id": 1, "created_by": 1, "unlimited": False}
    return {}

def gen_cases(field, lo, hi, drift_id):
    return [
        {"id": f"P0-{field}-below-min",  "category": "BOUNDARY", "priority": "P0",
         "source": f"drift:{drift_id}", "regression_reason": f"below min={lo}",
         "action": {"kind": "http", "method": "POST", "path": "/red-packets", "body": build_body(field, lo - 1 if field != "name" else 0)},
         "expected": {"http": 400, "db_no_write": True}},
        {"id": f"P0-{field}-at-min",     "category": "BOUNDARY", "priority": "P1",
         "source": f"drift:{drift_id}", "regression_reason": f"at min={lo}",
         "action": {"kind": "http", "method": "POST", "path": "/red-packets", "body": build_body(field, lo)},
         "expected": {"http": 201}},
        {"id": f"P0-{field}-at-max",     "category": "BOUNDARY", "priority": "P1",
         "source": f"drift:{drift_id}", "regression_reason": f"at max={hi}",
         "action": {"kind": "http", "method": "POST", "path": "/red-packets", "body": build_body(field, hi)},
         "expected": {"http": 201}},
        {"id": f"P0-{field}-above-max",  "category": "BOUNDARY", "priority": "P0",
         "source": f"drift:{drift_id}", "regression_reason": f"above max={hi}",
         "action": {"kind": "http", "method": "POST", "path": "/red-packets", "body": build_body(field, hi + 1 if field != "name" else 60)},
         "expected": {"http": 400, "db_no_write": True}},
    ]

def to_yaml(cases):
    lines = ["# Auto-generated by V9 §11 Drift -> Regression Generator", f"# cases: {len(cases)}", ""]
    for c in cases:
        lines.append(f"- id: {c['id']}")
        lines.append(f"  category: {c['category']}")
        lines.append(f"  priority: {c['priority']}")
        lines.append(f"  source: \"{c['source']}\"")
        lines.append(f"  regression_reason: \"{c['regression_reason']}\"")
        lines.append(f"  action:")
        lines.append(f"    kind: {c['action']['kind']}")
        lines.append(f"    method: {c['action']['method']}")
        lines.append(f"    path: {c['action']['path']}")
        lines.append(f"    body: {json.dumps(c['action']['body'], ensure_ascii=False)}")
        lines.append(f"  expected:")
        for k, v in c['expected'].items():
            if isinstance(v, bool): lines.append(f"    {k}: {str(v).lower()}")
            else:                  lines.append(f"    {k}: {v}")
        lines.append("")
    return "\n".join(lines)

def main():
    if not SUT.exists() or not E2E.exists():
        print(f"ERROR: missing {SUT} or {E2E}", file=sys.stderr); return 4
    sut_text  = SUT.read_text(encoding="utf-8")
    e2e_text  = E2E.read_text(encoding="utf-8")
    drift_doc = json.loads(DRIFT_IN.read_text(encoding="utf-8")) if DRIFT_IN.exists() else {"drifts": []}

    constraints = parse_constraints(sut_text)
    print(f"[V9] Parsed {len(constraints)} constraints from {SUT.name}:")
    for c in constraints:
        print(f"     - {c['field']}: [{c['min']}, {c['max']}]")

    all_cases = []
    for c in constraints:
        signals = test_signals(e2e_text, c["field"])
        near_lo = any(abs(c["min"] - s) <= 2 for s in signals)
        near_hi = any(abs(c["max"] - s) <= 2 for s in signals)
        drift_id = f"D-{c['field']}"
        in_drift_doc = any(d.get("id") == drift_id for d in drift_doc.get("drifts", []))
        if not (near_lo and near_hi) or in_drift_doc:
            all_cases.extend(gen_cases(c["field"], c["min"], c["max"], drift_id))

    OUT_YAML.parent.mkdir(exist_ok=True)
    OUT_YAML.write_text(to_yaml(all_cases), encoding="utf-8")
    OUT_JSON.write_text(json.dumps(all_cases, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"\n[V9] Generated {len(all_cases)} P0/P1 boundary cases")
    print(f"     yaml: {OUT_YAML}")
    print(f"     json: {OUT_JSON}")
    if not all_cases:
        print("[V9] No drift detected, no cases needed")
        return 0
    # 摘要
    by_field = {}
    for c in all_cases:
        f = c["id"].split("-")[1]  # P0-{field}-...
        by_field[f] = by_field.get(f, 0) + 1
    print("\n[V9] Per-field breakdown:")
    for f, n in by_field.items():
        print(f"     {f}: {n} cases (2 P0 reject + 1 P1 at-min + 1 P1 at-max)")

    # V9 自我判定：生成 ≥ 1 个 case 算成功
    return 0 if all_cases else 3

if __name__ == "__main__":
    sys.exit(main())
